[package]
name = "physarum-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.131.0"
rand = "*"
piston2d-opengl_graphics = "0.83.0"
image = "0.24.9"
rayon = "*"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
